### PR TITLE
feat: add skip_create_image to skip image creation

### LINKED ISSUE #35: ENH: Show custom image OCI as part of default output
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description
When creating an image (without verbose logging) useful information such as the source instance OCID are shown in the output. However, the custom image OCID is not shown which requires going elsewhere (e.g. the OCI Console) to locate it. Seems simple and reasonable to display that custom image OCID when the image is created just as the source instance OCID is shown. For example this is what we see today:

```
==> MyBase.oracle-oci.Base_alx7: Creating temporary ssh key for instance...
==> MyBase.oracle-oci.Base_alx7: Creating instance...
==> MyBase.oracle-oci.Base_alx7: Created instance (ocid1.instance.oc1. iad.anuwcl475r7bqc4gsftvqrrbsojsdly3vcycoikdpjtjjog75irop3xaefcq).
==> MyBase.oracle-oci.Base_alx7: Waiting for instance to enter 'RUNNING' state...

 . . .

==> MyBase.oracle-oci.Base_alx7: Creating image from instance...
==> MyBase.oracle-oci.Base_alx7: Image created.
==> MyBase.oracle-oci.Base_alx7: Terminating instance (ocid1.instance.oc1.iad.anuwcl475r7bqc4gsftvqrrbsojsdly3vcycoikdpjtjjog75irop3xaefcq)...
==> MyBase.oracle-oci.Base_alx7: Terminated instance.
Build 'MyBase.oracle-oci.Base_alx7' finished after 8 minutes 7 seconds.
```

Why not instead this…?

```
==> MyBase.oracle-oci.Base_alx7: Image created (ocid1.image.oc1.iad.rbsojsdly3vcycoikdpjtjjoanuwcl475r7bqc4gsftvqrg75irop3xaefcq)...
```

#### Use Case(s)

Convenience and consistency with existing output detail (e.g. instance OCID is shown, why not the image OCID which is arguably more pertinent for packer)

#### Potential configuration
* No change in usage

### LINKED ISSUE #38: Add option for skipping image creation
#### Description

Adding an option for skipping the image creation step.

#### Use Case(s)

When running Packer from an automated pipeline for testing, having a configuration option to skip the custom image creation step on OCI and just performing a dry-run is beneficial to ensure that the Packer configuration is valid before publishing the image.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### PR DESCRIPTION
**Pull request by Djelibeybi**
Also added the image OCID to the output which resolves #35.

Closes #35
Closes #38

Signed-off-by: Avi Miller <avi.miller@oracle.com>

### CODE REVIEW

**Comment by prydie** [comment]
Do other plugins have this functionality? It seems like a cross cutting concern that should be implemented outside of plugins or am I missing something?

**Comment by Djelibeybi** [comment]
Most of the other plugins already have this functionality already.

**Review by prydie — APPROVED** [review]
LGTM

**Comment by Djelibeybi** [comment]
Is it possible to get an ETA for when this might be merged and included in a release?

**Comment by Djelibeybi** [comment]
@azr @nywilken sorry to ping you directly, but any chance we can get this merged and a new release?

**Review by azr — APPROVED** [review]

**Pull request merged**
